if settings.startup[setting_multi_building].value then
    generatemulti("steam-engine", "double-steam-engine", 2)
    generatemulti("steam-engine", "quad-steam-engine", 4)
    generatemulti("bob-steam-engine-2", "double-bob-steam-engine-2", 2)
    generatemulti("bob-steam-engine-2", "quad-bob-steam-engine-2", 4)
    generatemulti("bob-steam-engine-3", "double-bob-steam-engine-3", 2)
    generatemulti("bob-steam-engine-3", "quad-bob-steam-engine-3", 4)
    generatemulti("bob-steam-engine-4", "double-bob-steam-engine-4", 2)
    generatemulti("bob-steam-engine-4", "quad-bob-steam-engine-4", 4)
    generatemulti("bob-steam-engine-5", "double-bob-steam-engine-5", 2)
    generatemulti("bob-steam-engine-5", "quad-bob-steam-engine-5", 4)
    generatemulti("steam-engine-6", "double-steam-engine-6", 2)
    generatemulti("steam-engine-6", "quad-steam-engine-6", 4)

    generatemulti("steam-turbine", "double-steam-turbine", 2)
    generatemulti("steam-turbine", "quad-steam-turbine", 4)
    generatemulti("bob-steam-turbine-2", "double-bob-steam-turbine-2", 2)
    generatemulti("bob-steam-turbine-2", "quad-bob-steam-turbine-2", 4)
    generatemulti("bob-steam-turbine-3", "double-bob-steam-turbine-3", 2)
    generatemulti("bob-steam-turbine-3", "quad-bob-steam-turbine-3", 4)
    generatemulti("steam-turbine-4", "double-steam-turbine-4", 2)
    generatemulti("steam-turbine-4", "quad-steam-turbine-4", 4)

    generatemulti("bob-solar-panel-small", "double-bob-solar-panel-small", 2)
    generatemulti("bob-solar-panel-small", "quad-bob-solar-panel-small", 4)
    generatemulti("bob-solar-panel-small-2", "double-bob-solar-panel-small-2", 2)
    generatemulti("bob-solar-panel-small-2", "quad-bob-solar-panel-small-2", 4)
    generatemulti("bob-solar-panel-small-3", "double-bob-solar-panel-small-3", 2)
    generatemulti("bob-solar-panel-small-3", "quad-bob-solar-panel-small-3", 4)
    generatemulti("solar-panel-small-4", "double-solar-panel-small-4", 2)
    generatemulti("solar-panel-small-4", "quad-solar-panel-small-4", 4)

    generatemulti("solar-panel", "double-solar-panel", 2)
    generatemulti("solar-panel", "quad-solar-panel", 4)
    generatemulti("bob-solar-panel-2", "double-bob-solar-panel-2", 2)
    generatemulti("bob-solar-panel-2", "quad-bob-solar-panel-2", 4)
    generatemulti("bob-solar-panel-3", "double-bob-solar-panel-3", 2)
    generatemulti("bob-solar-panel-3", "quad-bob-solar-panel-3", 4)
    generatemulti("solar-panel-4", "double-solar-panel-4", 2)
    generatemulti("solar-panel-4", "quad-solar-panel-4", 4)

    generatemulti("bob-solar-panel-large", "double-solar-panel-large", 2)
    generatemulti("bob-solar-panel-large", "quad-solar-panel-large", 4)
    generatemulti("bob-solar-panel-large-2", "double-bob-solar-panel-large-2", 2)
    generatemulti("bob-solar-panel-large-2", "quad-bob-solar-panel-large-2", 4)
    generatemulti("bob-solar-panel-large-3", "double-bob-solar-panel-large-3", 2)
    generatemulti("bob-solar-panel-large-3", "quad-bob-solar-panel-large-3", 4)
    generatemulti("solar-panel-large-4", "double-solar-panel-large-4", 2)
    generatemulti("solar-panel-large-4", "quad-solar-panel-large-4", 4)

    generatemulti("accumulator", "double-accumulator", 2)
    generatemulti("accumulator", "quad-accumulator", 4)
    generatemulti("bob-large-accumulator-2", "double-bob-large-accumulator-2", 2)
    generatemulti("bob-large-accumulator-2", "quad-bob-large-accumulator-2", 4)
    generatemulti("bob-large-accumulator-3", "double-bob-large-accumulator-3", 2)
    generatemulti("bob-large-accumulator-3", "quad-bob-large-accumulator-3", 4)
    generatemulti("accumulator-4", "double-accumulator-4", 2)
    generatemulti("accumulator-4", "quad-accumulator-4", 4)
end