-- GLOBAL NAME Liquid and Gas

-- BASE
water = "water"
steam = "steam"
crude_oil = "crude-oil"
lubricant = "lubricant"
thruster_fuel = "thruster-fuel"
thruster_oxidizer = "thruster-oxidizer"
ammonia_solution = "ammoniacal-solution"
ammonia = "ammonia"
fluorine = "fluorine"
lithium_brine = "lithium-brine"
fluoroketone_cold = "fluoroketone-cold"
fluoroketone_hot = "fluoroketone-hot"
electrolyte = "electrolyte"
heavy_oil = "heavy-oil"
molten_iron = "molten-iron"
molten_copper = "molten-copper"
sulfuric_acid = "sulfuric-acid"
lava = "lava"
fusion_plasma = "fusion-plasma"
petroleum_gas = "petroleum-gas"

-- ANGELS RESOURCE REFINING
sludge_ferrous = "angels-ore8-sludge"
slurry_ferrous = "angels-ore8-solution"
concentrate_anodized_ferrous = "angels-ore8-anode-sludge"
concentrate_ferrous = "angels-ore8-slime"
sludge_cupric = "angels-ore9-sludge"
slurry_cupric = "angels-ore9-solution"
concentrate_anodized_cupric = "angels-ore9-anode-sludge"
concentrate_cupric = "angels-ore9-slime"
water_thermal_angels = "angels-thermal-water"
slurry_slag = "angels-slag-slurry"
sludge_mineral = "angels-mineral-sludge"
slurry_crystal = "angels-crystal-slurry"
seedling_crystal = "angels-crystal-seedling"
iron_chloride_III_solution_angels = "angels-liquid-ferric-chloride-solution"
copper_chloride_II_solution_angels = "angels-liquid-cupric-chloride-solution"
milling_drum = "angels-milling-drum"
milling_drum_lubricated = "angels-milling-drum-lubricated"

-- ANGELS METALLURGY SMELTING
hexafluorosilicic_acid = "angels-liquid-hexafluorosilicic-acid"
trichlorosilane = "angels-liquid-trichlorosilane"
silane_gas = "angels-gas-silane"
chlorauric_acid = "angels-liquid-chlorauric-acid"
titanium_chloride_IV = "angels-liquid-titanium-tetrachloride"
ammonium_tungstate_solution = "angels-liquid-tungstic-acid"
tungsten_fluoride_VI_gas  = "angels-gas-tungsten-hexafluoride"
hexachloroplatinic_acid = "angels-liquid-hexachloroplatinic-acid"

-- ANGELS METALLURGY CASTING
iron_molten_angels = "angels-liquid-molten-iron"
steel_molten_angels = "angels-liquid-molten-steel"
copper_molten_angels = "angels-liquid-molten-copper"
lead_molten_angels = "angels-liquid-molten-lead"
tin_molten_angels = "angels-liquid-molten-tin"
manganese_molten_angels = "angels-liquid-molten-manganese"
silicon_molten_angels = "angels-liquid-molten-silicon"
nickel_molten_angels = "angels-liquid-molten-nickel"
aluminium_molten_angels = "angels-liquid-molten-aluminium"
zinc_molten_angels = "angels-liquid-molten-zinc"
silver_molten_angels = "angels-liquid-molten-silver"
titanium_molten_angels = "angels-liquid-molten-titanium"
gold_molten_angels = "angels-liquid-molten-gold"
cobalt_molten_angels = "angels-liquid-molten-cobalt"
chromium_molten_angels = "angels-liquid-molten-chrome"
platinum_molten_angels = "angels-liquid-molten-platinum"
glass_molten_angels = "angels-liquid-molten-glass"
concrete_liquid = "angels-liquid-concrete"
solder_molten_angels = "angels-liquid-molten-solder"
bronze_molten_angels = "angels-liquid-molten-bronze"
brass_molten_angels = "angels-liquid-molten-brass"
gunmetal_molten_angels = "angels-liquid-molten-gunmetal"
invar_molten_angels = "angels-liquid-molten-invar"
cobalt_steel_molten_angels = "angels-liquid-molten-cobalt-steel"
nitinol_molten_angels = "angels-liquid-molten-nitinol"

-- ANGELS WATER TREATMENT
water_semiheavy_1 = "angels-liquid-water-semiheavy-1"
water_semiheavy_2 = "angels-liquid-water-semiheavy-2"
water_semiheavy_3 = "angels-liquid-water-semiheavy-3"
water_heavy_angels = "angels-liquid-water-heavy"
water_purified_angels = "angels-water-purified"
water_mineralized_angels = "angels-water-mineralized"
coolant = "angels-liquid-coolant"
coolant_used = "angels-liquid-coolant-used"
water_yellow_waste = "angels-water-yellow-waste"
water_red_waste= "angels-water-red-waste"
water_green_waste = "angels-water-green-waste"
water_greenyellow_waste= "angels-water-greenyellow-waste"
water_viscous_mud = "angels-water-viscous-mud"
water_heavy_mud = "angels-water-heavy-mud"
water_concentrated_mud = "angels-water-concentrated-mud"
water_light_mud = "angels-water-light-mud"
water_thin_mud = "angels-water-thin-mud"
water_saline_angels = "angels-water-saline"

-- ANGELS PETROCHEM REFINING
compressed_air = "angels-gas-compressed-air"
oxygen_angels = "angels-gas-oxygen"
carbon_monoxide_angels = "angels-gas-carbon-monoxide"
carbon_dioxide_angels = "angels-gas-carbon-dioxide"
hydrogen_angels = "angels-gas-hydrogen"
deuterium_angels = "angels-gas-deuterium"
chlorine_angels = "angels-gas-chlorine"
hydrogen_chloride_angels = "angels-gas-hydrogen-chloride"
hydrochloric_acid_angels = "angels-liquid-hydrochloric-acid"
allyl_chloride_angels = "angels-gas-allylchlorid"
epichlorohydrin_angels = "angels-gas-epichlorohydrin"
chloromethane_angels = "angels-gas-chlor-methane"
perchloric_acid_angels = "angels-liquid-perchloric-acid"
sodium_hydroxide_solution_angels = "angels-liquid-aqueous-sodium-hydroxide"
nitrogen_angels = "angels-gas-nitrogen"
ammonia_angels = "angels-gas-ammonia"
nitrogen_monoxide_angels = "angels-gas-nitrogen-monoxide"
nitrogen_dioxide_angels = "angels-gas-nitrogen-dioxide"
dinitrogen_tetroxide_angels = "angels-gas-dinitrogen-tetroxide"
ammonium_chloride_solution_angels = "angels-gas-ammonium-chloride"
urea_solution_angels = "angels-gas-urea"
melamine_solution_angels = "angels-gas-melamine"
nitric_acid_angels = "angels-liquid-nitric-acid"
monochloramine_angels = "angels-gas-monochloramine"
hydrazine_angels = "angels-gas-hydrazine"
methylamine_angels = "angels-gas-methylamine"
dimethylamine_angels = "angels-gas-dimethylamine"
dimethylhydrazine_angels = "angels-gas-dimethylhydrazine"
nitroglycerin_bob = "bob-nitroglycerin"
hydrogen_sulfide_angels = "angels-gas-hydrogen-sulfide"
enriched_hydrogen_sulfide_angels = "angels-gas-enriched-hydrogen-sulfide"
sulfur_dioxide_angels = "angels-gas-sulfur-dioxide"
sulfuric_acid_angels = "angels-liquid-sulfuric-acid"

acid_angels = "angels-gas-acid"
hydrogen_fluoride_angels = "angels-gas-hydrogen-fluoride"
hydrofluoric_acid_angels = "angels-liquid-hydrofluoric-acid"
natural_gas_angels = "angels-gas-natural-1"
raw_gas_angels = "angels-gas-raw-1"
NGL_angels = "angels-liquid-ngl"
multi_phase_oil_angels = "angels-liquid-multi-phase-oil"
condensates_angels = "angels-liquid-condensates"
residual_angels = "angels-gas-residual"
methane_angels = "angels-gas-methane"
ethane_angels = "angels-gas-ethane"
butane_angels = "angels-gas-butane"
propene_angels = "angels-gas-propene"
methanol_angels = "angels-gas-methanol"
ethylene_angels = "angels-gas-ethylene"
benzene_angels = "angels-gas-benzene"
fuel_oil_angels = "angels-liquid-fuel-oil"
liquid_fuel_bob = "bob-liquid-fuel"
naphtha_angels = "angels-liquid-naphtha"
mineral_oil_angels = "angels-liquid-mineral-oil"
synthesis_angels = "angels-gas-synthesis"
toluene_angels = "angels-liquid-toluene"
butadiene_angels = "angels-gas-butadiene"
ethylbenzene_angels = "angels-liquid-ethylbenzene"
styrene_angels = "angels-liquid-styrene"
formaldehyde_angels = "angels-gas-formaldehyde"
glycerol_angels = "angels-liquid-glycerol"
acetone_angels = "angels-gas-acetone"
liquid_plastic_angels = "angels-liquid-plastic"
liquid_resin_angels = "angels-liquid-resin"
liquid_rubber_angels = "angels-liquid-rubber"

-- ANGELS BIOPROCESSING NAUVIS
yellow_fluid = "bob-alien-explosive"
purple_fluid = "bob-alien-acid"
green_fluid = "bob-alien-poison"
red_fluid = "bob-alien-fire"

-- ANGELS BIOPROCESSING VEGETABLES
nutrient_pulp = "angels-liquid-nutrient-pulp"
raw_vegetable_oil = "angels-liquid-raw-vegetable-oil"
vegetable_oil = "angels-liquid-vegetable-oil"
fermentation_fluid = "angels-liquid-fermentation-raw"
acetic_acid = "angels-liquid-acetic-acid"
acetic_anhydride = "angels-liquid-acetic-anhydride"
ethanol_angels = "angels-gas-ethanol"
propionic_acid = "angels-liquid-propionic-acid"

-- ANGELS BIOPROCESSING ANIMALIS
water_for_fish = "angels-liquid-fish-atmosphere"
polluted_water_for_fish = "angels-liquid-polluted-fish-atmosphere"
raw_fish_oil = "angels-liquid-raw-fish-oil"
fish_oil = "angels-liquid-fish-oil"
puffer_atmosphere = "angels-gas-puffer-atmosphere"
alien_spores = "angels-alien-spores"
alien_goo = "angels-alien-goo"

-- ???
sour_gas_bob = "bob-sour-gas"