-- BASE
space_age = "space-age"

-- MULUNA
muluna_mods = "planet-muluna"
planet_muluna = "muluna"
lunar_regolith = "muluna-lunar-regolith"
stone_crushed_mods = "stone-crushed"
alumina_mods = "alumina"
alumina_crushed = "alumina-crushed"
aluminium_plate_mods = "aluminum-plate"
molten_aluminium_mods = "molten-aluminum"
aluminium_plate_crushed = "aluminum-crushed"
aluminium_cable = "aluminum-cable"
aluminium_pipe = "bob-aluminium-pipe"
aluminium_pipe_to_ground = "bob-aluminium-pipe-to-ground"
cellulose_mods = "cellulose"
tar_mods = "tar"
diffused_plastic_muluna = "muluna-diffused-plastic"
heat = "muluna-heat"
vacuum_heating_tower = "muluna-vacuum-heating-tower"
satellite_radar = "muluna-satellite-radar"
cooled_steam_mods = "cooled-steam"
steam_crusher = "muluna-steam-crusher"
crusher_2 = "crusher-2"
cryolab = "cryolab"
astronomical_data_muluna = "muluna-astronomical-data"
telescope = "muluna-telescope"
oxygen_mods = "oxygen"
carbon_dioxide_mods = "carbon-dioxide"
anorthite_chunk = "anorthite-chunk"
interstellar_science_pack = "interstellar-science-pack"

-- MOSHINE
moshine_mods = "Moshine"
planet_moshine = "moshine"
datacell_empty = "datacell-empty"
silicon_boule_mods = "silicon"
silicon_cell_mods = "silicon-cell"
silicon_carbide_mods = "silicon-carbide"
glass_mods = "glass"
neodymium_mods = "neodymium"
neodymium_magnet = "magnet"
neural_computer = "neural_computer"
space_train_battery_pack = "space-train-battery-pack"

-- PANGLIA
panglia_mods = "panglia_planet"
planet_panglia = "panglia"
igneous_rock = "panglia_igneous_rock"
panglite = "panglia_panglite"
branbalite = "panglia_branbalite"
branbalite_slurry = "panglia_branbalite_slurry"
cloned_specimen_body_0 = "panglia_cloned_specimen_body_0"
cloned_specimen_body_1 = "panglia_cloned_specimen_body_1"
cloned_specimen_body_2 = "panglia_cloned_specimen_body_2"
cloned_specimen_body_3_genius = "panglia_cloned_specimen_body_3_genius"
cloned_specimen_body_3 = "panglia_cloned_specimen_body_3"
datacell_dna_raw = "datacell-dna-raw"
datacell_dna_sequenced = "datacell-dna-sequenced"
panglite_fiber = "panglia_panglite_fiber"
sentient_processor = "panglia_sentient_processor"
universe_precursor = "universe_precursor"
galaxy_png = "__matter_printer__/graphics/icons/galaxy.png"

-- ARIG
arig_mods = "planetaris-arig"
planet_arig = "arig"
cactus_arig = "planetaris-cactus"
raw_quartz_arig = "planetaris-raw-quartz"
glass_arig = "planetaris-glass-panel"
raw_diamond_arig = "planetaris-raw-diamond"
sand_arig = "planetaris-sand"
pure_sand_arig = "planetaris-pure-sand"
silica_arig = "planetaris-silica"
heavy_glass_arig = "planetaris-heavy-glass"
hyper_transport_belt_arig = "planetaris-hyper-transport-belt"
hyper_underground_belt_arig = "planetaris-hyper-underground-belt"
hyper_splitter_arig = "planetaris-hyper-splitter"
hyper_loader_arig = "mdrn-hyper-loader"
sandstone_brick = "planetaris-sandstone-brick"
sandstone_foundation = "planetaris-sandstone-foundation"
compression_science_pack = "planetaris-compression-science-pack"
rocket_biofuel = "planetaris-rocket-biofuel"
cactus_plastic = "planetaris-cactus-plastic-bar"

-- HYARION
hyarion_mods = "planetaris-hyarion"
planet_hyarion = "hyarion"
metallic_ore = "planetaris-metallic-ore"
carbon_ore = "planetaris-carbon-ore"
quartz_ore = "planetaris-quartz-ore"
polishing_compound_hyarion = "planetaris-polishing-compound"
charged_alexandrite_hyarion = "planetaris-charged-fluorite"
alexandrite_hyarion = "planetaris-fluorite"
aluminium_hyarion = "planetaris-aluminium"
raw_emerald_hyarion = "planetaris-raw-emerald"
raw_ruby_hyarion = "planetaris-raw-ruby"
raw_sapphire_hyarion = "planetaris-raw-sapphire"
polished_diamond_hyarion = "planetaris-polished-diamond"
polished_emerald_hyarion = "planetaris-polished-emerald"
polished_ruby_hyarion = "planetaris-polished-ruby"
polished_sapphire_hyarion = "planetaris-polished-sapphire"
polished_quartz_hyarion = "planetaris-polished-quartz"
raw_bismuth = "planetaris_raw_bismuth"
fiber_optics_cable = "planetaris-fiber-optics-cable"
simulating_unit = "planetaris-simulating-unit"
crystalization_motor = "planetaris-crystalization-motor"
beryllium_plate = "planetaris-beryllium-plate"
refractory_ceramics = "planetaris-refractory-ceramics"
polishing_science_pack = "planetaris-polishing-science-pack"
refraction_science_pack = "planetaris-refraction-science-pack"
polished_bismuth = "planetaris-polished-bismuth"
bismuth_transistor = "planetaris-bismuth-transistor"
geode_mining_drill = "hyarion-geode-mining-drill"
quartz_furnace = "planetaris-quartz-furnace"
refraction_ray_collector = "planetaris-refraction-ray-collector"
carbon_nanotube_hyarion = "planetaris-carbon-nanotube"
space_manufactorer = "planetaris-space-manufacturer"
zero_grav_accumulator = "planetaris-zero-grav-accumulator"
electromagnetic_radar = "planetaris-electromagnetic-radar"

-- TELLUS
tellus_mods = "planetaris-tellus"
planet_tellus = "tellus"
chlorophyll = "planetaris-chlorophyll"
magnesium_bacteria = "planetaris-magnesium-bacteria"
magnesium_dust = "planetaris-magnesium-dust"
magnesium_sheet = "planetaris-magnesium-sheet"
compost_tellus = "planetaris-compost"
water_infected = "planetaris-infected-water"
seed_compound = "planetaris-seed-compound"
arigian_bacteria = "planetaris-arigian-bacteria"
wasp_egg = "planetaris-wasp-egg"
bacteriochlorophyll = "planetaris-bacteriochlorophyll"
polimer_skin = "planetaris-polimer-skin"
unstable_bacteria = "planetaris-unstable-bacteria"
bioengineering_science_pack = "planetaris-bioengineering-science-pack"
pathological_science_pack = "planetaris-pathological-science-pack"
mushell_seed = "planetaris-mushell-seed"
pesticide = "planetaris-pesticide"
carbolyte_crust = "planetaris-carbolyte-crust"
volcanic_soil = "planetaris-volcanic-soil"
holmiumnite_bulb = "planetaris-holmiumnite-bulb"
dust_soil = "planetaris-dust-soil"
unstable_crystal = "planetaris-unstable-crystal"
mushroom_cap = "planetaris-mushroom-cap"
mycelia = "planetaris-mycelia"
mycelia_composite = "planetaris-mycelia-composite"
artificial_mycelia_soil = "planetaris-artificial-mycelia-soil"
overgrowth_mycelia_soil = "planetaris-overgrowth-mycelia-soil"
chloroplast_fruit = "planetaris-chloroplast-fruit"
chloroplast_mash = "planetaris-chloroplast-mash"
artificial_chlorophyll_soil = "planetaris-artificial-chlorophyll-soil"
overgrowth_chlorophyll_soil = "planetaris-overgrowth-chlorophyll-soil"

blue_dye = "planetaris-blue-dye"
yellow_dye = "planetaris-yellow-dye"
magenta_dye = "planetaris-magenta-dye"
green_dye = "planetaris-green-dye"
red_dye = "planetaris-red-dye"
cyan_dye = "planetaris-cyan-dye"
blue_pipe = "planetaris-blue-pipe"
yellow_pipe = "planetaris-yellow-pipe"
magenta_pipe = "planetaris-magenta-pipe"
green_pipe = "planetaris-green-pipe"
red_pipe = "planetaris-red-pipe"
cyan_pipe = "planetaris-cyan-pipe"
blue_pipe_to_ground = "planetaris-blue-pipe-to-ground"
yellow_pipe_to_ground = "planetaris-yellow-pipe-to-ground"
magenta_pipe_to_ground = "planetaris-magenta-pipe-to-ground"
green_pipe_to_ground = "planetaris-green-pipe-to-ground"
red_pipe_to_ground = "planetaris-red-pipe-to-ground"
cyan_pipe_to_ground = "planetaris-cyan-pipe-to-ground"
blue_concrete = "planetaris-blue-concrete"
yellow_concrete = "planetaris-yellow-concrete"
magenta_concrete = "planetaris-magenta-concrete"
green_concrete = "planetaris-green-concrete"
red_concrete = "planetaris-red-concrete"
cyan_concrete = "planetaris-cyan-concrete"

-- PARACELSIN
paracelsin_mods = "Paracelsin"
planet_paracelsin = "paracelsin"
sphalerite_ore = "sphalerite"
tetrahedrite_ore = "tetrahedrite"
vaterite = "vaterite"
zinc_mods = "zinc"
zinc_plate_mods = "zinc-plate"
zinc_rivets = "zinc-rivets"
zinc_cable = "zinc-solder"
galvanized_steel_plate = "galvanized-steel-plate"
nitrogen_mods = "nitrogen"
nitric_acid_mods = "nitric-acid"
galvanization_science_pack = "galvanization-science-pack"
galvanized_pipe = "zinc-pipe"
galvanized_pipe_to_ground = "zinc-pipe-to-ground"
galvanized_storage_tank = "zinc-storage-tank"
galvanized_pump = "zinc-pump"

-- CORRUNDUM
corrundum_mods = "corrundum"
planet_corrundum = "corrundum"
sulfur_dioxide_mods = "sulfur-dioxide"
calcium_sulfate_mods = "calcium-sulfate"
sulfur_ore_mods = "sulfur-ore"
platinum_ore_mods = "platinum-ore"
platinum_plate_mods = "platinum-plate"
chalcopyrite_ore = "chalcopyrite-ore"
electrochemical_science_pack = "electrochemical-science-pack"

-- SECRETAS / FROZETA
secretas_frozeta_mods = "secretas"
planet_secretas = "secretas"
planet_frozeta = "frozeta"
gold_ore_mods = "gold-ore"
gold_plate_mods = "gold-plate"
golden_biter_egg = "golden-biter-egg"
golden_science_pack = "golden-science-pack"

-- TERRAPALUS
terrapalus_mods = "terrapalus"
planet_terrapalus = "terrapalus"
palusium_ore = "palusium-ore"
palusium_powder = "palusium-powder"
palusium_crystal = "palusium-crystal"
palusium_plate = "palusium-plate"
ultravium = "ultravium"

-- CASTRA
castra_mods = "castra-prime"
planet_castra = "castra"
hydrogen_sulfide_mods = "hydrogen-sulfide"
castra_data = "castra-data"
nickel_plate_mods = "nickel-plate"
military_transport_belt_mods = "military-transport-belt"
military_underground_belt_mods = "military-underground-belt"
military_splitter_mods = "military-splitter"
millerite_ore = "millerite"
gunpowder = "gunpowder"
battlefield_science_pack = "battlefield-science-pack"

-- SHCHIERBIN
shchierbin_mods = "shchierbin"
planet_shchierbin = "shchierbin"
vanadium_ore = "vanadium-ore"
vanadium_oxide_V = "vanadium-oxide"
vanadium_plate = "vanadium-plate"
vanadium_steel_plate = "vanadium-steel-plate"
slaked_lime_mods = "slaked-lime"
quicklime_mods = "quicklime"
natural_gas_mods = "natural-gas"
methane_mods = "methane"
chloromethane_mods = "chloromethane"
ethylene_mods = "ethylene"
sea_water_mods = "sea-water"
sodium_hydroxide_mods = "sodium-hydroxide"
ferric_chloride_mods = "ferric-chloride"
chlorine_mods = "chlorine"
vinylchloride_mods = "vinylchloride"
calcium_mods = "calcium"
vanadium_science_pack = "vanadium-science-pack"
vanadium_electro_engine_unit = "vanadium-electro-engine-unit"
vanadium_crusher = "crusher-vanad"

-- MARAXSIS
maraxsis_mods = "maraxsis"
planet_maraxsis = "maraxsis"
planet_trench_maraxsis = "maraxsis-trench"
salt_mods = "salt"
sand_mods = "sand"
hydrogen_mods = "hydrogen"
supercritical_steam_maraxsis = "maraxsis-supercritical-steam"
water_brackish_maraxsis = "maraxsis-brackish-water"
maraxsis_air = "maraxsis-atmosphere"
molten_salt_mods = "molten-salt"
limestone_mods = "limestone"
glass_panes_maraxsis = "maraxsis-glass-panes"
water_saline_maraxsis = "maraxsis-saline-water"
hydraulic_science_pack = "hydraulic-science-pack"
super_sealant_substance_maraxsis = "maraxsis-super-sealant-substance"
tropical_fish_maraxsis = "maraxsis-tropical-fish"
coral_maraxsis = "maraxsis-coral"
salt_filter_maraxsis = "maraxsis-salt-filter"
saturated_salt_filter_maraxsis = "maraxsis-saturated-salt-filter"
empty_research_vessel = "maraxsis-empty-research-vessel"

-- VESTA
vesta_mods = "skewer_planet_vesta"
planet_vesta = "vesta"
algea_water_vesta = "ske_algea_water"
vesta_foundation = "vesta-foundation"
helium_vesta = "vesta_helium"
hydrogen_vesta = "vesta_hydrogen"
oxygen_vesta = "vesta_oxygen"
nitrogen_vesta = "vesta_nitrogen"
carbon_dioxide_vesta = "vesta_carbon_dioxide"
carbon_monoxide_vesta = "vesta_carbon"
hydrogen_sulfide_vesta = "vesta_hydrogen_sulfide"
methane_vesta = "vesta_methane"
deuterium_mods = "deuterium"
tritium_mods = "tritium"
algea_clump_iron = "ske_algea_clump_iron"
algea_clump_copper = "ske_algea_clump_copper"
iridium_plate_mods = "iridium-plate"
supermagnetic_vesta = "ske_supermagnetic"
gas_manipulation_science_pack = "gas-manipulation-science-pack"
algea_nutrient_clump = "algea_nutrient_clump"
algea_petrite_clump = "ske_algea_clump_petrite"
magnetic_pipe_vesta = "ske_magnetic_pipe"
electrolyzer_vesta = "vesta-electrolyzer"
fusion_thruster_fuel = "fluorofuel"
fusion_thruster_oxidizer = "plasmafuel"

-- SHATTERED
shattered_mods = "skewer_shattered_planet"
planet_shattered = "skewer_shattered_planet"
slurry_metallic_shattered = "ske_slurry_metallic"
slurry_carbonic_shattered = "ske_slurry_carbonic"
slurry_oxide_shattered = "ske_slurry_oxide"
slurry_promethium_shattered = "ske_slurry_promethium"
promethium_ore_shattered = "ske_promethium_ore"
brine_shattered = "ske_brine"
neon_mods = "neon"
argon_mods = "argon"
krypton_mods = "krypton"
xenon_mods = "xenon"
plutonium_238_shattered = "ske_plutonium_238"
plutonium_239_shattered = "ske_plutonium_239"
plutonium_241_shattered = "ske_plutonium_241"
plutonium_242_shattered = "ske_plutonium_242"
neptunium_236_shattered = "ske_neptunium_236"
neptunium_237_shattered = "ske_neptunium_237"
uranium_233_shattered = "ske_uranium_233"
uranium_235_shattered = "ske_uranium_235"
uranium_238_shattered = "ske_uranium_238"
americium_241_shattered = "ske_americium_241"
americium_242_shattered = "ske_americium_242"
americium_243_shattered = "ske_americium_243"
curium_245_shattered = "ske_curium_245"
curium_246_shattered = "ske_curium_246"
curium_247_shattered = "ske_curium_247"
berkelium_247_shattered = "ske_berkelium_247"
berkelium_248_shattered = "ske_berkelium_248"
californium_249_shattered = "ske_californium_249"
californium_250_shattered = "ske_californium_250"
californium_251_shattered = "ske_californium_251"
californium_252_shattered = "ske_californium_252"
graphite_shattered = "ske_graphite"
thorium_shattered = "ske_thorium"
plutonium_238_tiny = "ske_plutonium_238_tiny"
plutonium_239_tiny = "ske_plutonium_239_tiny"
plutonium_241_tiny = "ske_plutonium_241_tiny"
plutonium_242_tiny = "ske_plutonium_242_tiny"
neptunium_236_tiny = "ske_neptunium_236_tiny"
neptunium_237_tiny = "ske_neptunium_237_tiny"
uranium_233_tiny = "ske_uranium_233_tiny"
uranium_235_tiny = "ske_uranium_235_tiny"
uranium_238_tiny = "ske_uranium_238_tiny"
americium_241_tiny = "ske_americium_241_tiny"
americium_242_tiny = "ske_americium_242_tiny"
americium_243_tiny = "ske_americium_243_tiny"
curium_245_tiny = "ske_curium_245_tiny"
curium_246_tiny = "ske_curium_246_tiny"
curium_247_tiny = "ske_curium_247_tiny"
berkelium_247_tiny = "ske_berkelium_247_tiny"
berkelium_248_tiny = "ske_berkelium_248_tiny"
californium_249_tiny = "ske_californium_249_tiny"
californium_250_tiny = "ske_californium_250_tiny"
californium_251_tiny = "ske_californium_251_tiny"
californium_252_tiny = "ske_californium_252_tiny"
heu_science_pack = "ske_heu_science_pack"
hep_science_pack = "ske_hep_science_pack"
hea_science_pack = "ske_hea_science_pack"
hec_science_pack = "ske_hec_science_pack"
hef_science_pack = "ske_hef_science_pack"
antimatter_cell = "ske_antimatter_cell"

-- MURIA
muria_mods = "Muria"
planet_muria = "muria"
muriatic_solution = "muriatic-solution"
hydronium_solution = "hydronium"
eschatotaxite_sprout = "eschatotaxite-sprout"
chlorine_salts = "chlorine-salts"
acidophile_lichen = "acidophile-lichen"
cotunnite = "cotunnite"
leaded_fuel = "leaded-fuel"
inert_muriatic_science_pack = "inert-muriatic-science-pack"
muriatic_science_pack = "muriatic-science-pack"
anti_corrosion_cladding = "anti-corrosion-cladding"

-- PELAGOS
pelagos_mods = "pelagos"
planet_pelagos = "pelagos"
coconut = "coconut"
coconut_oil = "coconut-oil"
coconut_sealant = "coconut-sealant"
fermentation_bacteria = "fermentation-bacteria"
ethanol_mods = "ethanol"
titanium_sludge = "titanium-sludge"
titanium_dust = "titanium-dust"
titanium_plate_mods = "titanium-plate"
spoilage_science_pack = "pelagos-science-pack"
activated_carbon = "activated-carbon"
biodiesel = "biodiesel"
captive_copper_biter_spawner = "captive-copper-biter-spawner"
capture_robot_rocket_pelagos = "pelagos-capture-robot-rocket"
titanium_barrel = "titanium-barrel"

-- APIA and CARNOVA
apia_carnova_mods = "apia"
planet_apia = "apia"
planet_carnova = "carnova"
phosphoric_acid = "phosphoric-acid"
royal_jelly = "royal-jelly"
honeycombs = "honeycombs"
wax = "wax"
honey = "honey"
polysaccharides = "polysaccharides"
bones = "bones"
flesh = "flesh"
lymph = "lymph"
dirty_lymph = "dirty-lymph"
blood = "blood"
lipids = "lipids"
proteins = "proteins"
piranha_roe = "piranha-roe"
glycerine = "glycerine"
apicultural_science_pack = "apicultural-science-pack"
wax_platform = "wax-platform"
biosynthesizer = "biosynthesizer"
artificial_hive = "artificial-hive"

-- FOLIAX
foliax_mods = "foliax"
planet_foliax = "foliax"
burner_agricultural_tower_foliax = "foliax-burner-agricultural-tower"

-- OBSIDIAX
obsidiax_mods = "obsidiax"
planet_obsidiax = "obsidiax"
foundry_obsidiax = "obsidiax-foundry"
foundry_ice_obsidiax = "obsidiax-ice-foundry"
obsidian_cube_sp = "obsidiax-obsidian-cube"

-- CRUCIBLE
crucible_mods = "planet-crucible"
planet_crucible = "crucible"

-- RIBBONIA
ribbonia_mods = "ribbonia"
planet_ribbonia = "ribbonia"

-- LINOX
linox_mods = "linox"
planet_linox = "linox"
lava_data_card = "linox-item_lava-data-card"
rare_data_card = "linox-item_rare-earth-data-card"
samarium_data_card = "linox-item_samarium-data-card"
dysprosium_data_card = "linox-item_dysprosium-data-card"
neodymium_data_card = "linox-item_neodymium-data-card"

-- REGIA
reigia_mods = "reigia"
planet_reigia = "reigia"

-- CUBIUM
cubium_mods = "cubium"
planet_cubium = "cubium"

-- NEXUS
nexus_mods = "Nexus"
planet_nexus= "nexus"

-- VUCLANUS SULFURIC BACTERIA
vulcanus_sulfuric_bacteria_mods = "vulcanus-sulfuric-bacteria"
sulfuric_bacteria = "sulfuric-bacteria"

-- CLOWNS NUCLEAR
clowns_nuclear = "Clowns-Nuclear"
plutonium_239_mods = "plutonium-239"

-- BOBS
bobenemies = "bobenemies"
bobequipment = "bobequipment"
boblogistics = "boblogistics"
bobmodules = "bobmodules"
bobores = "bobores"
bobplates = "bobplates"
bobtech = "bobtech"
bobvehicleequipment = "bobvehicleequipment"
bobwarfare = "bobwarfare"

-- ANGELS
angelspetrochem = "angelspetrochem"

-- LOADERS MODERNIZED
loaders_modernized_integrations = "loaders-modernized-integrations"

-- SPACE AGE SCIENCE PACK
space_age_science_packs = "sa-science-packs"

-- PRIZMATIC BELTS
prismatic_belts = "prismatic-belts"

-- RESKINS
reskins_library = "reskins-library"
reskins_bobs = "reskins-bobs"

-- SOLAR PRODUCTIVITY
solar_productivity = "solar-productivity"

-- ASTEROID BETL
asteroid_belt_mods = "AsteroidBelt"

-- TELOGISTICS
telogistics_mods = "Telogistics"