-- MULUNA
muluna_mods = "planet-muluna"
planet_muluna = "muluna"
lunar_regolith = "muluna-lunar-regolith"
stone_crushed_mods = "stone-crushed"
alumina_mods = "alumina"
alumina_crushed = "alumina-crushed"
aluminium_plate_mods = "aluminum-plate"
molten_aluminium_mods = "molten-aluminum"
aluminium_plate_crushed = "aluminum-crushed"
aluminium_cable = "aluminum-cable"
cellulose_mods = "cellulose"
tar_mods = "tar"
diffused_plastic_muluna = "muluna-diffused-plastic"
heat = "muluna-heat"
vacuum_heating_tower = "muluna-vacuum-heating-tower"
satellite_radar = "muluna-satellite-radar"
cooled_steam_mods = "cooled-steam"
steam_crusher = "muluna-steam-crusher"
astronomical_data_muluna = "muluna-astronomical-data"
telescope = "muluna-telescope"
oxygen_mods = "oxygen"
carbon_dioxide_mods = "carbon-dioxide"
anorthite_chunk = "anorthite-chunk"

-- ARIG
arig_mods = "planetaris-arig"
planet_arig = "arig"
cactus_arig = "planetaris-cactus"
raw_quartz_arig = "planetaris-raw-quartz"
glass_panel_arig = "planetaris-glass-panel"
raw_diamond_arig = "planetaris-raw-diamond"
sand_arig = "planetaris-sand"
pure_sand_arig = "planetaris-pure-sand"
silica_arig = "planetaris-silica"
heavy_glass_arig = "planetaris-heavy-glass"
hyper_transport_belt_arig = "planetaris-hyper-transport-belt"
hyper_underground_belt_arig = "planetaris-hyper-underground-belt"
hyper_splitter_arig = "planetaris-hyper-splitter"
sandstone_brick = "planetaris-sandstone-brick"

-- CASTRA
castra_mods = "castra"
planet_castra= "castra"
hydrogen_sulfide_mods = "hydrogen-sulfide"
castra_data = "castra-data"
nickel_plate_mods = "nickel-plate"
military_transport_belt_mods = "military-transport-belt"
military_underground_belt_mods = "military-underground-belt"
military_splitter_mods = "military-splitter"
millerite_mods = "millerite"
gunpowder_mods = "gunpowder"

-- CORRUNDUM
corrundum_mods = "corrundum"
planet_corrundum = "corrundum"
sulfur_dioxide_mods = "sulfur-dioxide"
calcium_sulfate_mods = "calcium-sulfate"
sulfur_ore_mods = "sulfur-ore"
platinum_ore_mods = "platinum-ore"
platinum_plate_mods = "platinum-plate"
sulfuric_acid_dilute_mods = "sulfuric-acid-dilute"
mixed_sulfate_solution_mods = "mixed-sulfate-solution"
iron_sulfate_solution_mods = "iron-sulfate-solution"
copper_sulfate_solution_mods = "copper-sulfate-solution"

-- CUBIUM
cubium_mods = "cubium"
planet_cubium = "cubium"

-- SECRETAS / FROZETA
secretas_frozeta_mods = "secretas"
planet_frozeta = "frozeta"
gold_ore_mods = "gold-ore"
gold_plate_mods = "gold-plate"
speed_module_4_S = "speed-module-4-S"
efficiency_module_4_S = "efficiency-module-4-S"
productivity_module_4_S = "productivity-module-4-S"
quality_module_4_S = "quality-module-4-S"

-- HYARION
hyarion_mods = "planetaris-hyarion"
planet_hyarion = "hyarion"
polishing_compound_hyarion = "planetaris-polishing-compound"
charged_fluorite_hyarion = "planetaris-charged-fluorite"
fluorite_hyarion = "planetaris-fluorite"
aluminium_hyarion = "planetaris-aluminium"
raw_emerald_hyarion = "planetaris-raw-emerald"
raw_ruby_hyarion = "planetaris-raw-ruby"
raw_sapphire_hyarion = "planetaris-raw-sapphire"
polished_diamond_hyarion = "planetaris-polished-diamond"
polished_emerald_hyarion = "planetaris-polished-emerald"
polished_ruby_hyarion = "planetaris-polished-ruby"
polished_sapphire_hyarion = "planetaris-polished-sapphire"
polished_quartz_hyarion = "planetaris-polished-quartz"
raw_bismuth = "planetaris_raw_bismuth"
fiber_optics_cable = "planetaris-fiber-optics-cable"
simulating_unit = "planetaris-simulating-unit"
beryllium_plate = "planetaris-beryllium-plate"
refractory_ceramics = "planetaris-refractory-ceramics"
bismuth_transistor = "planetaris-bismuth-transistor"

-- MARAXSIS
maraxsis_mods = "maraxsis"
planet_maraxsis = "maraxsis"
planet_trench_maraxsis = "maraxsis-trench"
salt_mods = "salt"
sand_mods = "sand"
hydrogen_mods = "hydrogen"
supercritical_steam_maraxsis = "maraxsis-supercritical-steam"
water_brackish_maraxsis = "maraxsis-brackish-water"
liquid_atmosphere_maraxsis = "maraxsis-liquid-atmosphere"
atmosphere_maraxsis = "maraxsis-atmosphere"
molten_salt_mods = "molten-salt"
limestone_mods = "limestone"
glass_panes_maraxsis = "maraxsis-glass-panes"
water_saline_maraxsis = "maraxsis-saline-water"
super_sealant_substance_maraxsis = "maraxsis-super-sealant-substance"
tropical_fish_maraxsis = "maraxsis-tropical-fish"
coral_maraxsis = "maraxsis-coral"
salt_filter_maraxsis = "maraxsis-salt-filter"
saturated_salt_filter_maraxsis = "maraxsis-saturated-salt-filter"

-- MOSHINE
moshine_mods = "Moshine"
planet_moshine = "moshine"
datacell_empty = "datacell-empty"
silicon_boule_mods = "silicon"
silicon_cell_mods = "silicon-cell"
silicon_carbide_mods = "silicon-carbide"
glass_mods = "glass"

-- NEXUS
nexus_mods = "Nexus"
planet_nexus= "nexus"

-- PANGLIA
panglia_mods = "panglia_planet"
planet_panglia = "panglia"
branbalite_panglia = "panglia_branbalite"
branbalite_slurry_panglia = "panglia_branbalite_slurry"
cloned_specimen_body_0 = "panglia_cloned_specimen_body_0"
cloned_specimen_body_1 = "panglia_cloned_specimen_body_1"
cloned_specimen_body_2 = "panglia_cloned_specimen_body_2"
cloned_specimen_body_3_genius = "panglia_cloned_specimen_body_3_genius"
cloned_specimen_body_3 = "panglia_cloned_specimen_body_3"
datacell_dna_raw = "datacell-dna-raw"
datacell_dna_sequenced = "datacell-dna-sequenced"
panglite_fiber = "panglia_panglite_fiber"
sentient_processor = "panglia_sentient_processor"
galaxy_png = "__matter_printer__/graphics/icons/galaxy.png"

-- PARACELSIN
paracelsin_mods = "Paracelsin"
planet_paracelsin = "paracelsin"
zinc_mods = "zinc"
zinc_plate_mods = "zinc-plate"
nitrogen_mods = "nitrogen"
nitric_acid_mods = "nitric-acid"
zinc_concentrate_mods = "zinc-concentrate"
dirty_zinc_solution_mods = "dirty-zinc-solution"
zinc_solution_mods = "zinc-solution"
zinc_solder_mods = "zinc-solder"

-- SHATTERED
shattered_mods = "skewer_shattered_planet"
planet_shattered = "skewer_shattered_planet"
slurry_promethium_shattered = "ske_slurry_promethium"
slurry_carbonic_shattered = "ske_slurry_carbonic"
slurry_metallic_shattered = "ske_slurry_metallic"
slurry_oxide_shattered = "ske_slurry_oxide"
liquid_nitrogen_shattered = "ske_liquid_nitrogen"
brine_shattered = "ske_brine"
helium_mods = "helium"
neon_mods = "neon"
argon_mods = "argon"
krypton_mods = "krypton"
xenon_mods = "xenon"
plutonium_238_shattered = "ske_plutonium_238"
plutonium_239_shattered = "ske_plutonium_239"
plutonium_241_shattered = "ske_plutonium_241"
plutonium_242_shattered = "ske_plutonium_242"
neptunium_236_shattered = "ske_neptunium_236"
neptunium_237_shattered = "ske_neptunium_237"
uranium_233_shattered = "ske_uranium_233"
uranium_235_shattered = "ske_uranium_235"
uranium_238_shattered = "ske_uranium_238"
americium_241_shattered = "ske_americium_241"
americium_242_shattered = "ske_americium_242"
americium_243_shattered = "ske_americium_243"
curium_245_shattered = "ske_curium_245"
curium_246_shattered = "ske_curium_246"
curium_247_shattered = "ske_curium_247"
berkelium_247_shattered = "ske_berkelium_247"
berkelium_248_shattered = "ske_berkelium_248"
californium_249_shattered = "ske_californium_249"
californium_250_shattered = "ske_californium_250"
californium_251_shattered = "ske_californium_251"
californium_252_shattered = "ske_californium_252"
promethium_shattered = "ske_promethium_ore"
graphite_shattered = "ske_graphite"
thorium_shattered = "ske_thorium"
plutonium_238_tiny = "ske_plutonium_238_tiny"
plutonium_239_tiny = "ske_plutonium_239_tiny"
plutonium_241_tiny = "ske_plutonium_241_tiny"
plutonium_242_tiny = "ske_plutonium_242_tiny"
neptunium_236_tiny = "ske_neptunium_236_tiny"
neptunium_237_tiny = "ske_neptunium_237_tiny"
uranium_233_tiny = "ske_uranium_233_tiny"
uranium_235_tiny = "ske_uranium_235_tiny"
uranium_238_tiny = "ske_uranium_238_tiny"
americium_241_tiny = "ske_americium_241_tiny"
americium_242_tiny = "ske_americium_242_tiny"
americium_243_tiny = "ske_americium_243_tiny"
curium_245_tiny = "ske_curium_245_tiny"
curium_246_tiny = "ske_curium_246_tiny"
curium_247_tiny = "ske_curium_247_tiny"
berkelium_247_tiny = "ske_berkelium_247_tiny"
berkelium_248_tiny = "ske_berkelium_248_tiny"
californium_249_tiny = "ske_californium_249_tiny"
californium_250_tiny = "ske_californium_250_tiny"
californium_251_tiny = "ske_californium_251_tiny"
californium_252_tiny = "ske_californium_252_tiny"
heu_science_pack = "ske_heu_science_pack"
hep_science_pack = "ske_hep_science_pack"
hea_science_pack = "ske_hea_science_pack"
hec_science_pack = "ske_hec_science_pack"
hef_science_pack = "ske_hef_science_pack"
antimatter_cell = "ske_antimatter_cell"

-- SHCHIERBIN
shchierbin_mods = "shchierbin"
planet_shchierbin = "shchierbin"
quicklime_mods = "quicklime"
natural_gas_mods = "natural-gas"
methane_mods = "methane"
chloromethane_mods = "chloromethane"
ethylene_mods = "ethylene"
sea_water_mods = "sea-water"
sodium_hydroxide_mods = "sodium-hydroxide"
ferric_chloride_mods = "ferric-chloride"
chlorine_mods = "chlorine"
vinylchloride_mods = "vinylchloride"
calcium_mods = "calcium"

-- TERRAPALUS
terrapalus_mods = "terrapalus"
planet_terrapalus = "terrapalus"
ultravium = "ultravium"
palusium_powder = "palusium-powder"

-- VESTA
vesta_mods = "skewer_planet_vesta"
planet_vesta = "vesta"
algea_water_vesta = "ske_algea_water"
dt_fuel = "ske_dt_fuel"
helium_vesta = "vesta_helium"
hydrogen_vesta = "vesta_hydrogen"
oxygen_vesta = "vesta_oxygen"
nitrogen_vesta = "vesta_nitrogen"
carbon_dioxide_vesta = "vesta_carbon_dioxide"
carbon_monoxide_vesta = "vesta_carbon"
hydrogen_sulfide_vesta = "vesta_hydrogen_sulfide"
methane_vesta = "vesta_methane"
tritium_mods = "tritium"
deuterium_mods = "deuterium"
iridium_plate_mods = "iridium-plate"
supermagnetic_vesta = "ske_supermagnetic"
fluoro_fuel = "fluorofuel"
plasma_fuel = "plasmafuel"

-- VUCLANUS SULFURIC BACTERIA
vulcanus_sulfuric_bacteria_mods = "vulcanus-sulfuric-bacteria"
sulfuric_bacteria = "sulfuric-bacteria"

-- CLOWNS NUCLEAR
clowns_nuclear = "Clowns-Nuclear"
plutonium_239_mods = "plutonium-239"

-- BOBS
bobtech = "bobtech"

-- LOADERS MODERNIZED
loaders_modernized = "loaders-modernized"

-- SPACE AGE SCIENCE PACK
space_age_science_packs = "sa-science-packs"