tech_electronics_0 = "electronics"
tech_steam_power = "steam-power"


tech_electric_substation_4 = "bob-electric-substation-4"

tech_robotics_1 = "robotics"
tech_robotics_2 = "bob-robotics-2"
tech_robotics_3 = "bob-robotics-3"
tech_robotics_4 = "bob-robotics-4"
tech_robots_1 = "bob-robots-1"
tech_robots_2 = "bob-robots-2"
tech_robots_3 = "bob-robots-3"
tech_robots_4 = "bob-robots-4"
tech_robo_modular_1 = "bob-robo-modular-1"
tech_construction_robotics = "construction-robotics"
tech_logistic_robotics = "logistic-robotics"

tech_steam_turbine_1 = "bob-steam-turbine-1"
tech_fluid_generator_1 = "bob-fluid-generator-1"
tech_solar_energy_1 = "solar-energy"
tech_solar_energy_2 = "bob-solar-energy-2"
tech_solar_energy_3 = "bob-solar-energy-3"
tech_solar_energy_4 = "bob-solar-energy-4"
tech_electric_energy_accumulators_1 = "electric-energy-accumulators"
tech_electric_energy_accumulators_2 = "bob-electric-energy-accumulators-2"
tech_electric_energy_accumulators_3 = "bob-electric-energy-accumulators-3"
tech_electric_energy_accumulators_4 = "bob-electric-energy-accumulators-4"
tech_drills_2 = "bob-drills-2"
tech_drills_3 = "bob-drills-3"
tech_drills_4 = "bob-drills-4"
tech_drills_5 = "bob-drills-5"
tech_drills_6 = "bob-drills-6"
tech_area_drills_1 = "bob-area-drills-1"
tech_area_drills_2 = "bob-area-drills-2"
tech_area_drills_3 = "bob-area-drills-3"
tech_area_drills_4 = "bob-area-drills-4"
tech_pumpjacks_2 = "bob-pumpjacks-2"
tech_pumpjacks_3 = "bob-pumpjacks-3"
tech_pumpjacks_4 = "bob-pumpjacks-4"
tech_pumpjacks_5 = "bob-pumpjacks-5"
tech_pumpjacks_6 = "bob-pumpjacks-6"
tech_heat_exchanger_1 = "bob-heat-exchanger-1"
tech_advanced_material_processing_4 = "advanced-material-processing-4"
tech_advanced_material_processing_5 = "advanced-material-processing-5"
tech_multi_purpose_furnace_2 = "bob-multi-purpose-furnace-2"
tech_multi_purpose_furnace_3 = "bob-multi-purpose-furnace-3"
tech_automation_1 = "automation"
tech_automation_2 = "automation-2"
tech_automation_3 = "automation-3"
tech_automation_4 = "automation-4"
tech_automation_5 = "automation-5"
tech_automation_6 = "automation-6"
tech_logistics_0 = "logistics-0"
tech_logistics_1 = "logistics"
tech_logistics_2 = "logistics-2"
tech_logistics_3 = "logistics-3"
tech_logistics_4 = "logistics-4"
tech_logistics_5 = "logistics-5"
tech_T3_inserter = "bob-express-inserter"

tech_bronze_processing = "bob-alloy-processing"
tech_steel_processing = "steel-processing"
tech_plastic_processing = "plastics"
tech_brass_processing = "bob-brass-processing"
tech_cobalt_processing = "bob-cobalt-processing"
tech_ceramics = "bob-ceramics"
tech_titanium_processing = "bob-titanium-processing"
tech_nitinol_processing = "bob-nitinol-processing"
tech_tungsten_processing = "bob-tungsten-processing"
tech_tungsten_alloy_processing = "timsaba-tungsten-alloy-processing"
tech_lithium_processing = "bob-lithium-processing"
tech_battery_2 = "bob-battery-2"
tech_battery_3 = "bob-battery-3"
tech_battery_4 = "bob-battery-4"
tech_electronics = "bob-electronics"

tech_heat_shield = "bob-heat-shield"

tech_uranium_power = "nuclear-power"
tech_uranium_processing = "uranium-processing"
tech_plutonium_based_power_systems = "kovarex-enrichment-process"
tech_uranium_power_2 = "bob-nuclear-power-2"
tech_uranium_power_3 = "bob-nuclear-power-3"
tech_tritium_power = "bob-nuclear-power-4"

tech_uranium_ammo = "uranium-ammo"
tech_military_2 = "military-2"
tech_military_3 = "military-3"
tech_military_4 = "military-4"

tech_modules_2 = "bob-modules-2"
tech_modules_3 = "bob-modules-3"
tech_modules_4 = "bob-modules-4"
tech_modules_5 = "bob-modules-5"

tech_exoskeleton_eq_2 = "bob-exoskeleton-equipment-2"

tech_gun_turret_5 = "bob-turrets-5"

tech_sniper_turret_2 = "bob-sniper-turrets-2"

tech_laser_turret_4 = "bob-laser-turrets-4"
tech_laser_turret_5 = "bob-laser-turrets-5"

tech_plasma_turret_3 = "bob-plasma-turrets-3"
tech_plasma_turret_4 = "bob-plasma-turrets-4"

tech_fluid_handling_4 = "bob-fluid-handling-4"

tech_artillery = "artillery"

tech_tank_2 = "bob-tanks-2"
tech_tank_3 = "bob-tanks-3"

tech_alien_research = "bob-alien-research"