tech_robotics = "robotics"
tech_robo_modular_1 = "bob-robo-modular-1"

tech_steam_turbine_1 = "bob-steam-turbine-1"
tech_fluid_generator_1 = "bob-fluid-generator-1"
solar_energy_2 = "bob-solar-energy-2"
solar_energy_3 = "bob-solar-energy-3"
solar_energy_4 = "solar-energy-4"
electric_energy_accumulators_1 = "electric-energy-accumulators"
electric_energy_accumulators_2 = "bob-electric-energy-accumulators-2"
electric_energy_accumulators_3 = "bob-electric-energy-accumulators-3"
electric_energy_accumulators_4 = "electric-energy-accumulators-4"
drills_5 = "bob-drills-5"
drills_6 = "drills-6"
tech_pumpjacks_3 = "bob-pumpjacks-3"
tech_pumpjacks_5 = "pumpjacks-5"
tech_pumpjacks_6 = "pumpjacks-6"
tech_heat_exchanger_1 = "bob-heat-exchanger-1"
advanced_material_processing_4 = "advanced-material-processing-4"
advanced_material_processing_5 = "advanced-material-processing-5"
multi_porpose_furnace_2 = "bob-multi-porpose-furnace-2"
multi_porpose_furnace_3 = "multi-porpose-furnace-3"
automation_5 = "automation-5"

tech_steel_processing = "steel-processing"
tech_zinc_processing = "bob-zinc-processing"
tech_brass_processign = "bob-zinc-processing"
tech_ceramics = "bob-ceramics"
tech_titanium_processing = "bob-titanium-processing"
tech_tungsten_processing = "bob-tungsten-processing"
tech_tungsten_alloy_processing = "bob-tungsten-alloy-processing"
tech_lithium_processing = "bob-lithium-processing"
battery_2 = "bob-battery-2"
battery_3 = "bob-battery-3"
battery_4 = "battery-4"
tech_electronics = "bob-electronics"

tech_nuclear_power = "nuclear-power"
tech_uranium_processing = "uranium-processing"

tech_uranium_ammo = "uranium-ammo"
tech_military_4 = "military-4"