if mods[cubium_mods] then
    data.raw["recipe"]["express-transport-belt-dream"].subgroup = "cubium-logistics"
    data.raw["recipe"]["express-underground-belt-dream"].subgroup = "cubium-logistics"
    data.raw["recipe"]["express-splitter-dream"].subgroup = "cubium-logistics"
    data.raw["recipe"]["turbo-transport-belt-dream"].subgroup = "cubium-logistics"
    data.raw["recipe"]["turbo-underground-belt-dream"].subgroup = "cubium-logistics"
    data.raw["recipe"]["turbo-splitter-dream"].subgroup = "cubium-logistics"

    data.raw["recipe"]["dream-small-power-pole"].subgroup = "cubium-building"
    data.raw["item"]["cube-smasher"].subgroup = "cubium-building"
    data.raw["recipe"]["cube-smasher"].subgroup = "cubium-building"
    data.raw["recipe"]["cube-smasher-cubic"].subgroup = "cubium-building"
    data.raw["recipe"]["dream-foundry"].subgroup = "cubium-building"
    data.raw["recipe"]["dream-electromagnetic-plant"].subgroup = "cubium-building"

    data.raw["recipe"]["angry-ammunition"].subgroup = "cubium-war"
    data.raw["recipe"]["angry-rockets"].subgroup = "cubium-war"

    data.raw["recipe"]["cube-jelly-awaken"].subgroup = "cubium-energized"
    data.raw["recipe"]["cubic-latent-recovery"].subgroup = "cubium-energized"
    data.raw["recipe"]["metallic-aggravation"].subgroup = "cubium-energized"
    data.raw["recipe"]["solid-fuel-massage"].subgroup = "cubium-energized"
    data.raw["recipe"]["cubic-recovery"].subgroup = "cubium-energized"
    data.raw["recipe"]["steam-bath"].subgroup = "cubium-energized"

    data.raw["recipe"]["dormant-cube-smashing"].subgroup = "cubium-energized-shards"
    data.raw["recipe"]["space-cube-recovery"].subgroup = "cubium-energized-shards"
    data.raw["recipe"]["ammonia-intoxication"].subgroup = "cubium-energized-shards"
    data.raw["recipe"]["inverted-shards"].subgroup = "cubium-energized-shards"

    data.raw["recipe"]["inverted-cube"].subgroup = "cubium-inverted"
    data.raw["recipe"]["recharge-inverted-cube"].subgroup = "cubium-inverted"

    data.raw["item"]["energized-microcube"].subgroup = "cubium-items"
    data.raw["item"]["dormant-microcube"].subgroup = "cubium-items"
    data.raw["item"]["inverted-microcube"].subgroup = "cubium-items"
    data.raw["item"]["inverted-dormant-microcube"].subgroup = "cubium-items"
    data.raw["item"]["ultradense-substrate"].subgroup = "cubium-items"
    data.raw["item"]["energized-shards"].subgroup = "cubium-items"
    data.raw["item"]["inverted-shards"].subgroup = "cubium-items"
    data.raw["item"]["cube-jelly"].subgroup = "cubium-items"
    data.raw["item"]["inverted-cube-jelly"].subgroup = "cubium-items"
    data.raw["item"]["dream-fuel"].subgroup = "cubium-items"
    data.raw["item"]["destabilized-cube-matter"].subgroup = "cubium-items"
    data.raw["item"]["dream"].subgroup = "cubium-items"

    data.raw["fluid"]["liquid-anger"].subgroup = "cubium-fluids"
    data.raw["fluid"]["liquid-courage"].subgroup = "cubium-fluids"
    data.raw["fluid"]["liquid-disgust"].subgroup = "cubium-fluids"
    data.raw["fluid"]["liquid-fear"].subgroup = "cubium-fluids"
    data.raw["fluid"]["liquid-hate"].subgroup = "cubium-fluids"
    data.raw["fluid"]["liquid-hope"].subgroup = "cubium-fluids"
    data.raw["fluid"]["ultradense-lava"].subgroup = "cubium-fluids"
    data.raw["fluid"]["dream-concentrate"].subgroup = "cubium-fluids"
    data.raw["fluid"]["emotional-tar"].subgroup = "cubium-fluids"
    data.raw["fluid"]["liquid-dream"].subgroup = "cubium-fluids"

    data.raw["recipe"]["solid-fuel-from-hope-and-dream"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["energized-microcube"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["carbonic-scaffolding"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["cube-jelly-basic"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["cube-jelly-ore-basic"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["cube-jelly-plastic"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["cube-jelly-to-solid-fuel"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["dream-amplification"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["matter-amplification"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["cube-jelly-ore-advanced-iron"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["cube-jelly-ore-advanced-copper"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["dream-overflow"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["sulfuric-acid-inversion"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["ultradense-substrate"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["inverted-amplification"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["jelly-inversion"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["engine-unit-by-inversion"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["light-oil-by-inversion"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["dream-advanced-circuit"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["dream-concrete"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["dream-processing-unit"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["electric-engine-unit-by-inversion"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["refined-dream-concrete"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["rocket-fuel-dreams"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["carbon-inversion"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["hope-spoilage"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["biter-egg-breeding"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["ice-dreams"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["dream-holmium-plate"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["biter-egg-refresh"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["cube-jelly"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["dream-fuel"].subgroup = "cubium-recipe-item"
    data.raw["recipe"]["inverted-cube-jelly-recycling"].subgroup = "cubium-recipe-item"

    data.raw["recipe"]["dream-concentrate"].subgroup = "cubium-recipe-fluid"
    data.raw["recipe"]["emotional-tar"].subgroup = "cubium-recipe-fluid"
    data.raw["recipe"]["liquid-dream"].subgroup = "cubium-recipe-fluid"
    data.raw["recipe"]["cube-jelly-to-steam"].subgroup = "cubium-recipe-fluid"
    data.raw["recipe"]["inversion-awakening"].subgroup = "cubium-recipe-fluid"
    data.raw["recipe"]["petrol-gas-by-inversion"].subgroup = "cubium-recipe-fluid"
    data.raw["recipe"]["anger-cracking"].subgroup = "cubium-recipe-fluid"
    data.raw["recipe"]["anger-reconstitution"].subgroup = "cubium-recipe-fluid"
    data.raw["recipe"]["courage-fear-steam"].subgroup = "cubium-recipe-fluid"
    data.raw["recipe"]["emotional-cracking"].subgroup = "cubium-recipe-fluid"
    data.raw["recipe"]["fear-inversion"].subgroup = "cubium-recipe-fluid"
    data.raw["recipe"]["biter-egg-to-dream"].subgroup = "cubium-recipe-fluid"

    data.raw["recipe"]["automation-science-pack-cubic"].subgroup = "cubium-science"
    data.raw["recipe"]["chemical-science-pack-cubic"].subgroup = "cubium-science"
    data.raw["recipe"]["logistic-science-pack-cubic"].subgroup = "cubium-science"
    data.raw["recipe"]["military-science-pack-cubic"].subgroup = "cubium-science"
    data.raw["recipe"]["production-science-pack-cubic"].subgroup = "cubium-science"
    data.raw["recipe"]["utility-science-pack-cubic"].subgroup = "cubium-science"

    data.raw["recipe"]["electrochemical-science-pack-cubic"].subgroup = "corrundum-science"
    data.raw["recipe"]["agricultural-science-pack-cubic"].subgroup = "gleba-science"
    data.raw["recipe"]["cryogenic-science-pack-cubic"].subgroup = "aquilo-science"
    data.raw["recipe"]["electromagnetic-science-pack-cubic"].subgroup = "fulgora-science"
    data.raw["recipe"]["metallurgic-science-pack-cubic"].subgroup = "vulcanus-science"
    --data.raw["recipe"]["promethium-science-pack-cubic"].subgroup = "nexus-science"
    --data.raw["recipe"]["golden-science-pack-cubic"].subgroup = "frozeta-science"
end